version: "3"
# docker-compose -f docker-compose.yml up --detach --build  ## for recreating the change
services:
  am-api:
    image: zelejs/allin-web:jdk11
    container_name: am-api
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./api:/webapps  
      - ./nginx-gateway/attachments:/attachments
      #- ./swagger/app:/swagger/app
    environment:
      DL_STANDALONE: "am-pack-1.0.0-standalone.jar"

  am-io:
    image: zelejs/allin-web:jdk11
    container_name: am-io
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./io:/webapps
    environment:
      DL_STANDALONE: "zero-io-all-1.0.0-standalone.jar"

  am-web:
    image: daocloud.io/library/nginx:latest
    container_name: am-web
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./web/dist:/usr/share/nginx/html
      - ./web/logs:/var/log/nginx
 
  nginx-gateway:
    image: daocloud.io/library/nginx:latest
    container_name: nginx-gateway
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./nginx-gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-gateway/conf.d:/etc/nginx/conf.d
      - ./nginx-gateway/logs:/var/log/nginx
      #- ./nginx-gateway/cert:/cert
      - ./nginx-gateway/html:/usr/share/nginx/html
      - ./nginx-gateway/attachments:/usr/share/nginx/html/attachments
    ports:
      - '80:80'

  am-redis:
    container_name: am-redis
    image: 'daocloud.io/library/redis:3.2.9'
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - 6379:6379
    volumes:
      - ./redis/conf:/usr/local/etc/redis
    command:
      redis-server /usr/local/etc/redis/redis.conf

  am-mysql:
    container_name: am-mysql
    image: 'daocloud.io/library/mysql:5.7'
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: 'ems'
      MYSQL_ROOT_PASSWORD: 'ems@ceiec'
    volumes:
      - ./mysql/data:/var/lib/mysql
      #- ./mysql/config/my.cnf:/etc/my.cnf
      - ./mysql/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
