version: "3.8"
# docker-compose -f docker-compose.yml up --detach --build  ## for recreating the change
services:
  api:
    image: ceiec-ems:api
    container_name: am-api
    # healthcheck:
    #   test: "(JVM running for "
    build: 
      context: .
      dockerfile: ./Dockerfile.release.api
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./bin/attachments:/attachments
      # config
      - ./api/config:/webapps/config
      # - ./io/excel-templates:/webapps/excel-templates
    depends_on:
      - db

  # io:
  #   image: ceiec-ems:io
  #   build: 
  #     context: .
  #     dockerfile: ./Dockerfile.release.io
  #   container_name: am-io
  #   privileged: true
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro

  web:
    image: ceiec-ems:web
    build: 
      context: .
      dockerfile: ./Dockerfile.release.web
    container_name: am-web
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/var/log/nginx
      - ./gateway/conf.d:/etc/nginx/conf.d
      #- ./gateway/cert:/cert
      - ./web/static:/usr/share/nginx/html/static
      - ./web/config.js:/usr/share/nginx/html/config.js
      - ./bin/attachments:/usr/share/nginx/html/attachments
    ports:
      - '8000:80'
    depends_on: 
      - api

  # dependency
  db:
    # run db >>>
    # docker-compose run --name mysqlserver --service-ports mysqlserver
    # <<<
    container_name: am-db
    image: 'daocloud.io/library/mysql:5.7'
    privileged: true
    restart: always
    # healthcheck:
    #   test: "mysqld: ready for connections."
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: 'ems'
      # MYSQL_ROOT_PASSWORD: 'ems@ceiec'
      MYSQL_ROOT_PASSWORD: root
    command: 
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    volumes:
      # - ./mysql/data:/var/lib/mysql
      - ceiec_ems_data:/var/lib/mysql
      - ./mysql/mysql.conf.d/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
      - ./mysql/am.sql:/docker-entrypoint-initdb.d/schema.sql
    # ports:
    #   - 3306:3306
                
  redis:
    image: 'daocloud.io/library/redis:3.2.9'
    container_name: redis
    privileged: true
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./redis/conf:/usr/local/etc/redis
    command:
      redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

volumes: 
  ceiec_ems_data:

networks: 
  default:
     name: ceiec_network
     
