version: "3"
# docker-compose -f docker-compose.yml up --detach --build  ## for recreating the change
services:
  api:
    image: ceiec-ems:api
    container_name: am-api
    build: 
      context: .
      dockerfile: ./Dockerfile.release.api
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./attachments:/attachments
      # config
      - ./api/config:/webapps/config
    depends_on:
      - redis
      - mysqlserver
    command: for dev
      - "java"
      - "-jar"
      - "/webapps/app.jar"
      - "--spring.profiles.active=greenfield"
  io:
    image: ceiec-ems:io
    build: 
      context: .
      dockerfile: ./Dockerfile.release.io
    container_name: am-io
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro

  web:
    image: ceiec-ems:web
    build: 
      context: .
      dockerfile: ./Dockerfile.release.web
    container_name: am-web
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./gateway/conf.d:/etc/nginx/conf.d
      #- ./gateway/cert:/cert
      - ./logs:/var/log/nginx
      - ./attachments:/usr/share/nginx/html/attachments
    ports:
      - '8000:80'

  # dependency
  mysqlserver:
    container_name: mysqlserver
    image: 'daocloud.io/library/mysql:5.7'
    privileged: true
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_DATABASE: 'ems'
      MYSQL_ROOT_PASSWORD: 'ems@ceiec'
    # 初始化mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql_mode.cnf:/etc/mysql/mysql.conf.d/sql_mode.cnf
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 3306:3306
                
  redis:
    image: 'daocloud.io/library/redis:3.2.9'
    container_name: redis
    privileged: true
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./redis/conf:/usr/local/etc/redis
    command:
      redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
