---
spring:
  profiles: greenfield
  datasource:
      url: jdbc:mysql://mysqlserver:3306/ems?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: ems@ceiec
      filters: log4j,stat,mergeStat
      sql-script-encoding: UTF-8
      schema: classpath*:sql/*-schema.sql
      data: classpath*:sql/*-data.sql
      initialize: true 
