am:
  file-host: /attachments
  file-upload-path: /attachments 

PoolConfig:
    dateFormat: zh  

---
spring:
  profiles: produce
  datasource:
      url: jdbc:mysql://am-mysql:3306/ems?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: ems@ceiec
      filters: log4j,wall,mergeStat
      sql-script-encoding: UTF-8
      schema: classpath*:sql/*-schema.sql
      data: classpath*:sql/*-data.sql
      initialize: false

logging:
  level: warn 
  config: config/logback-spring.xml
am:
  redis-host: am-redis
  redis-port: 6379
