spring:
  profiles: produce
  datasource:
    url: jdbc:mysql://am-mysql/ems?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: ems@ceiec
    filters: log4j,wall,mergeStat
    sql-script-encoding: UTF-8
    schema: classpath*:sql/*-schema.sql
    data: classpath*:sql/*-data.sql
    initialize: false
---
io:
  excel-template-dir: "excel-templates"

logging:
  level: warn
  config: config/logback-spring.xml
